# https://taskfile.dev

version: "2"

tasks:
  initEnvironment:
    desc: Initialize CI environment
    cmds:
      - |
        asdf install \
          && terraform init \
          && cd examples/complete \
          && terraform init

  validatePreCommitHooks:
    desc: Validate the pre-commit hooks
    cmds:
      - pre-commit install
      - pre-commit run -a

  lint:
    desc: Run linter
    cmds:
      - docker run -it -v $(pwd):/src codacy/codacy-remark-lint:dev
